@startuml 
class models.Animal{
    nombre:string
    edad:int
    cuidador_id:int 
    especie_id:int
    recinto_id:int
    cuidador_id:int
}
 
class models.Cuidador{
    nombre:string
    apellido:string
    edad:int    id:int
    telefono:string
    especialidad:string
}
class models.Recinto{
    nombre:string
    capacidad:int
}
class models.Especie{
    nombre:string
    recinto_id:int
}
 
class models.Actividad{
    nombre:string
    dia:int
    horario:string 
    descripcion:text
}

class controllers.AnimalController{
    resource()
}
class controllers.CuidadorController{
    resource()
}
class controllers.RecintoController{
    resource()
}
class controllers.EspecieController{
    resource()
}
class controllers.ActividadController{
    resource()
}

models.Especie "1"*--"*" models.Animal
models.Recinto "1"--"*" models.Especie
models.Recinto "1"*--"*" models.Animal
models.Cuidador "1"*--"*" models.Animal
models.Actividad "1"*--"*" models.Animal
@enduml