<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

//Generated By PlantUML Command
class Animal extends Model
{
    protected $fillable = [
        'nombre',
        'edad',
        'cuidador_id',
        'especie_id',
        'recinto_id',
        'cuidador_id',
    ];

    public function especie()
    {
        return $this->belongsTo('App\Models\Especie');
    }

    public function recinto()
    {
        return $this->belongsTo('App\Models\Recinto');
    }

    public function cuidador()
    {
        return $this->belongsTo('App\Models\Cuidador');
    }

    public function actividad()
    {
        return $this->belongsTo('App\Models\Actividad');
    }
}
